### ISSUE TITLE
No friction is applied

### ISSUE THREAD

**Issue by SpelecAnton** [BirDt/bhop3d#1]
I'm using: v4.2.1.stable.mono.official [b09f793f5]

So I installed this addon into my project, but player isn't slowing down (like it's on ice)
Friction setting doesn't do anything. Same results appear in debug_world.tscn bundled with this addon

**Comment by BirDt** [comment]
This was a stupid typo in the [frame_timer and bhop_frames comparison](https://github.com/BirDt/bhop3d/blob/main/addons/bhop3d/src/bhop3d.gd#L104), which should now be fixed with 2f8e7b1 and [v1.1](https://github.com/BirDt/bhop3d/releases/tag/v1.1) (this should be updated on the asset store soon).
